const colorGradients = {
  "ff4351": "linear-gradient(#F36F74, #F2585E)",
  "fd6631": "linear-gradient(#FF8E73, #FF7C5C)",
  "fe9949": "linear-gradient(#F8AE5F, #F7A145)",
  "fec418": "linear-gradient(#E8CA45, #E5C238)",
  "ffd426": "linear-gradient(#53CD6B, #37C553)",
  "19bd03": "linear-gradient(#57CFB4, #2AC7A8)",
  "55dae1": "linear-gradient(#5ACCDE, #3FC4D9)",
  "1b9af7": "linear-gradient(#24BAF7, #00AFF6)",
  "3871de": "linear-gradient(#5874CA, #3D5EC2)",
  "7b72e9": "linear-gradient(#9164C7, #7F4BBE)",
  "db49d8": "linear-gradient(#C085E6, #B671E2)",
  "ed4694": "linear-gradient(#F694D8, #F583D2)",
  "000000": "linear-gradient(#9099A3, #7E8994)",
  "b4b2a9": "linear-gradient(#9DA79D, #8D998E)",
  "a9a9a9": "linear-gradient(#A49995, #968984)"
}
const shortcutColors = ["FF4351", "FD6631", "FE9949", "FEC418", "FFD426", "19BD03", "55DAE1", "1B9AF7", "3871DE", "7B72E9", "DB49D8", "000000", "ED4694", "B4B2A9", "A9A9A9"];
let iOS = (navigator.userAgent.match(/iP.+? OS (\d+)/) || [])[1];
let macApp = navigator.userAgent.match(/Macintosh/i) != null;
if (macApp) {
    // need to distinguish between Macbook and iPad
    let canvas = document.createElement("canvas");
    if (canvas != null) {
        var context =
            canvas.getContext("webgl") || canvas.getContext("experimental-webgl");
        if (context) {
            var info = context.getExtension("WEBGL_debug_renderer_info");
            if (info) {
                var renderer = context.getParameter(info.UNMASKED_RENDERER_WEBGL);
                if (renderer.indexOf("Apple") != -1) iOS = "13";
            }
        }
    }
}

function closestShortcutColor(color) {
    function dist(s, t) {
        if (!s.length || !t.length)
            return 0;
        return dist(s.slice(2), t.slice(2)) + Math.abs(parseInt(s.slice(0, 2), 16) - parseInt(t.slice(0, 2), 16));
    }
    if (!color) {
        color = "000000"
    }
    return shortcutColors.sort(function(a, b) {
        return dist(a, color) - dist(b, color);
    })[0].toLowerCase();
}

function makeShortcutURL(url, name, color) {
    color = parseInt(color, 16);
    var plist = `
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>WFWorkflowActions</key>
	<array>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.comment</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>WFCommentActionText</key>
				<string>Generated by @easrng's Shortcut install banner script.</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.url</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>WFURLActionURL</key>
				<string>${url}</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.showwebpage</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
	</array>
	<key>WFWorkflowClientRelease</key>
	<string>2.2.2</string>
	<key>WFWorkflowClientVersion</key>
	<string>788</string>
	<key>WFWorkflowIcon</key>
	<dict>
		<key>WFWorkflowIconGlyphNumber</key>
		<integer>59717</integer>
		<key>WFWorkflowIconImageData</key>
		<data>
             
		</data>
		<key>WFWorkflowIconStartColor</key>
		<integer>${color}</integer>
	</dict>
	<key>WFWorkflowImportQuestions</key>
	<array/>
	<key>WFWorkflowInputContentItemClasses</key>
	<array>
		<string>WFAppStoreAppContentItem</string>
		<string>WFArticleContentItem</string>
		<string>WFContactContentItem</string>
		<string>WFDateContentItem</string>
		<string>WFEmailAddressContentItem</string>
		<string>WFGenericFileContentItem</string>
		<string>WFImageContentItem</string>
		<string>WFiTunesProductContentItem</string>
		<string>WFLocationContentItem</string>
		<string>WFDCMapsLinkContentItem</string>
		<string>WFAVAssetContentItem</string>
		<string>WFPDFContentItem</string>
		<string>WFPhoneNumberContentItem</string>
		<string>WFRichTextContentItem</string>
		<string>WFSafariWebPageContentItem</string>
		<string>WFStringContentItem</string>
		<string>WFURLContentItem</string>
	</array>
	<key>WFWorkflowTypes</key>
	<array>
		<string>WatchKit</string>
	</array>
</dict>
</plist>
`
    let data = "data:application/octet-stream;base64," + btoa(plist);
    if (iOS == "13" || iOS == "14") {
        url =
            "shortcuts://x-callback-url/run-shortcut?name=Get%20Non-iCloud%20Shortcut&input=text&text=" +
            encodeURIComponent(JSON.stringify({
                url: data,
                name
            })) +
            "&x-error=https%3A%2F%2Fshortcutlink.glitch.me%2Ferror.html%3Fname%3DGet%2520Non-iCloud%2520Shortcut%26uri%3Dhttps://www.icloud.com/shortcuts/2f8453a254944961a49ae86240ef57ef";
    } else if (iOS == "12") {
        url =
            "shortcuts://import-workflow?url=" +
            encodeURIComponent(data) +
            "&name=" +
            encodeURIComponent(name);
    }
    return url;
}

if (iOS && !navigator.standalone && localStorage.getItem("_shortcutInstalled") != "1") {
    let siteName = document.title;
    try {
        siteName=document.querySelector('meta[name="apple-mobile-web-app-title"]').content
    } catch (e) {}
    let color="7B72E9"
    try {
        color = document.querySelector('meta[name="theme-color"]').content.slice(1);
    } catch (e) {}
    color = closestShortcutColor(color);
    let url = makeShortcutURL(document.location.href, siteName, color + "FF");
    var t = document.createElement("div")
    t.setAttribute("style", "all:initial;box-sizing:border-box;font-family:system-ui,-apple-system,sans-serif;background-color: #f2f2f7;width: 100%;position:fixed;top:0;left:0;display:flex;flex-direction:row;padding: 0 16px 0 10px;align-items:center;height: 64px;transform: translateY(-64px);")
    t.innerHTML = `<div style="text-align: center;"><a href="javascript:;" style="color: #aac8ed;text-decoration:none;padding: 5px;width: 10px;height: fit-content;display: inline-flex;align-items: center;justify-content: center;margin-bottom: 4px;" onclick="localStorage.setItem('_shortcutInstalled','1');document.querySelector(':root').style.transform='';this.parentElement.parentElement.remove();"><svg style="width: 8px;" viewBox="0 0 22 24"><g xmlns="http://www.w3.org/2000/svg" style="fill:none;fill-opacity:1;stroke:#b0c7ea;stroke-opacity:1;stroke-width: 2.6;stroke-linecap: round;stroke-linejoin: miter;transform: translate(-50.5px, -87.6px);" id="g856"><path d="M 70.245452,88.972644 51.96117,110.01789"></path><path d="M 51.96117,88.972644 70.245452,110.01789"></path></g></svg></a></div><div style="box-sizing:border-box;margin-left: 3px;width: 48px;height: 48px;border-radius:0.8em;
        background: ${colorGradients[color]};padding:0.2em;border: 1px solid #cecece;display: flex;align-items: center;justify-content: center;"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK4AAACuCAYAAACvDDbuAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAA21SURBVHhe7ZyLkSs3DkVfLBuLY3FOjmVjcSzP506Tds+MNFID4LdxqliulZokCNwGQWre/kqS5Kb8/v37f++20iVJ2lNE90dpf9L+Ku3/pf19sdV+dRyNqbFT3ImNIp4q0LMwe3AW9idBF/OS5ECiKOKoGbSXSK9QxZxCvjMl+DWjzijUV8jmmpFTxDujAJdAS6w7cc7GKeIdUCBLQFfNrFepmfiP4oJkJRS4EsA7iPUZmYVXgSBJsLuVAl5qFk4BzwZBScG+JsuIWVAQaCnYa2QGHgVOT8H6SQH3Qk4uzk7ikID/LC5OopFzi5OTNmgHy/o3CjmzODXpQ5YPXnDgbFlWtqjpRVKA1WSjml6wd1p9Xn01jtpsO4nsyex7FZymWnZ0lj0LtApTdoVnozpumUNzzSLmzL7vgqMUuBFBOwv1Q6TFpCFo/tJqdh4lZPkkxfsMOYemAPWkilXimDo4so92zsg9kZ/y5uErOEVB6RWMZcT6E9guEffOxH+V6ROcoQD0cL7m2K5m03po8qFexh5+1Dz3Lh1wQI96dvns+i5aI61HFr6veFm4xNSS2wj2K1ozrbWANfa9rsxYcMtDmByaBwnAD60FfB/xstBWov0QLO3e9dcD5BNay2Sxd6Jgga2cp3FTsC/AR/UQ14I9xcvCWoj2fnWWE/zVsnzYS7wsqIVoM8s6wHetsu8e4mUh0aLNLBsEfmxV+64dHxYQfeV13/vDhuDT6B+B1k0uGB4t2iwNGiLf0iJLB4l3rXhhcOQbrHHyXrYD+Dm6dFhnh5ShtEjRZj3bGXweKt4y7LxgZOR2k6IdCL6PLPXm/qsyGXjY6SYPYRNADCTeqN1zznJPhh32uUnRTgSxiDqvzLeDyqBimJcU7YQQk/3iK0OKQV7kmBTtpBCbqB11jnpXhhz2uJhvG0m+QYyixDs21jLgsMNFinYhiFVUohqzu2piWkSJkD8uLAYxixDvmJJBEx/zu8h/NbogxC0qafXdaTUhzXvKnP8XleQpxC/iF9K+twxlQg/japwbIl/TdLDSLqnYyf/6r6tMo3/EGadPqchEEcbmYawD+LkK9qfM6CrX1P8Yxkz7JKYJaN5sm3VtY/DxO4I9Y04k9J1fE0zgvcfTArNEaIR8S7si2IrrvEF/75mnXdbVwGUCD1kiNAC/WgVbcR+UGcNbMrTJugzszbZZIgSDTyVYCcabUCKE6y0ZtIbYxMaA3myrvlkiBCFf0iIEWwlJKozjPbjHJjcG9Gbb/HUsAPwYLdhKWKZjLG/WjUtwDOYxJg9kTuQ/WgvBitD4aCyax86YrMtA3vSfBzIj8h2tlWAr4bshY8pmKzFZl0Fc2bYMk1wAv/UQrIgRyRc0Zhnbiu9lYgCvAZltLyB/0TzZ6irNzh6M7VmHr3yhs2vyMkzyAnwlwXp2NgtNsm1FY5c5rNiSHh3HpvsbgI9GCLbSPD7M4Ul8tkMaHeVUK03f5tXBNyMFK7rEhzm0Tmvys9lIJ8/bktn2AfhltGAr3eLDXJ71XrOTDp4yIbPtCfmCph9wZhCs6Bof5vLs3NfOSXToN9mm4IfZBFvpuhsyX78kyMOeMuHWV2CsvwrWGqyWDNkNmbN92cmDWSYY0Lppswq2MuQv9JjXs4O/ZzMPtp9kI1jzCoIVQ5MKc1tLpvfs5iEFwcptygTWuopgK0OTiuY/zDDxWlc81PbNWBytkaYgrCJYMTw2zO/ZyX+uc3nAU99ufZvA+lYUbGV4CYcN7bTFA+3eikVhXSsLVgzPthXssJYLP6+BL7O+PaE10VYVbGWaAzO2tNEXX2Z9W2A9Kx28njFVXGTLh1U2Hu/ofJH1bYH17JBpxVTXk9jj0djjtfCFZ9Bt6lvW4vHDTGgN05Vv2GTd1R8nR77wHMy2qW9Zi+e+cSamyrYV7LLWuXoRv5c9fBg74IJoHWU9OzBlMpFdh3kmHgq3zVXFQrCOXbLttGcObFNysPL9ZeTD2NpjMVhHZLbVOLWNYNrSDdtiz1J8aBXulLXUVbSOYzlmFAyNoa1QwTk3lWHybw8hT59IZONh6mU+a40PPG/B8sJlDZ71Cwn2ZbmkZ2jWoL3L9AdlbJxCuMtfhbEGT31/WSj0afXjxhJlG3Za/f15fXzgEe70b/hPYL917SbRVuhrvcX5iSVigZ3WtT8UrpXVhWt1onunYQxvXX1mmUMytlp9/ncZ4oAPbvnjA7Zbs22ISBjHs9N9ZZk4yNbD5MvIV/+dJfgfMQMtBrYPy7YVxorIustkW4G9KVwrsrvYf5XQNTOWZ7erLHVAxt4UrhXsjjkgOGE8b7mwVLYV2BwmXHOxTFtOuLK52G4hXCga8xjaxHLXkdicwrWAzdb1ipmEq34r+j+FexXZW+y2MlOpsOSPP9idNe5VsNeTbUXomjVWGfMqy/m+gt0p3CvI1mKzl7A7U8ayvkhLZluB7cOFK1YSrjfbVsL+sIixLPXtstlWYPsUwl3l9/GobCs0jnvdjHG7bCtk/7GMy3wTrieoqwg3KttWXCd69aVZfP45eAuC/dZYfD4Y84FHuEu8/djpuSt9hqlkoJ/8bbVn6WwrWMMUf9Y4vSOx0VMKveJS5uVZ2WL19fLZVrAGq3C/Jwo+tGaA6f8FBDa2yLZnJCgF46mo+E6C9f5BzfS+fgfWEac1PrQOFv5LUiTY1zLbfkUClh8l0HOzZtgzu2Tb2N2dD63ZYGqHYlvrbNuLXbKtR7jfLwL4MOaKYiKwq2e2bckW2VawDk9MHgo3dsAJwK7MtpPBWmITpD4sX1qY7mYBmzLbTghrsZakj89SfOER7nQZAZt2yLaKxxI/8LwL64m/BNCXxzOX+fyvLweDPTtk2x1F22ZX50trGhfTbGfYsnq23U60Qmv6WJ2N5/7Ql8czJqaoc7Fj5WwrwSp5bFPTnilrsyC/PPeJviwPWZiizsWOFbPt1oKtsL74+raih45nL/PzW9EB5l8t295CsEJrLOu18Dop6qHjWRND6zLmXyXb3kawFdbq+bPS17rSQ8ezJoaVC8y9Qra9nWArrLntTq6HysMWhl2LMbdnp2iN/KmMczvBCq27+MDC+3/EpYePPia6lwuak2Z1TEtuLdhK8YGV92+r9PDRx0T3ckFzHlNPQwr2BH7wJML3faiHadYMpn7dAqa5ypwzkIL9gnxR/GLh+t96q9PR10S3HyOYa4Zsm4J9Aj7xxOe6jtTp6Gvi+ptigHlGZ1u93CnYJ8gvNGt81O+6X9WpdLbS/JDGHKOyrQQ79M56BfDRmORHZ48wmmZdxh+RbVOwFyj+smIvN+nsvdRvFmTG7pltU7AXwV+ebGsrE84wgOetaZJ1GbdXtk3BGim+s+K/UmUQz5sjwgPPmK2zbQrWAb7zZlu/7xnEm91Csy7jtcy2KVgn+E/xmWOXZrBpsi5jtci2Kdgg8OM8OzSDubMuLeSuk3Gisq3G0UuQgg0CX061O3/AoN5M5/41jTEiyoQUbCOKXz3Ex4RBvaJRX1fWpb/neq4KNn/lagB+9V6dtrv3Z3Bv/eIyjv6WlycF2xj5tvjZQ7sdkMEjDHSVDPR/98Sagu1E8bOHdtm2wiTerCtBmd8u9S1jPCMF2xH87C0RXHq4BBN57umE65aBvnKWxqgC1n9TsJ2Rr4vfPfT7hwdM5n3LhNtgxpDjZEuKdQD43ZvAJPq+sWNCb10juv3BeRILsVsz/kwasU2of96nLgYx855zRPsD2TOYPGIB/beLxAyxenU4fofxCQsDIrYM12Et6QMxihCtGF8iYkREySBSvBOj2NBC4lyGHA/GRNwyiBTvhCgmJTZeJPy54otBESWDSPFOhGJRYhLBnAdxDItaYIp3AhSDEosIhv0fIr4E46LqIJHiHQi+jzqIiXnq2mdgZOiCaSnezuDzyBjOV9c+A0Mj7ncrWnj+SNEJfK3YRYp2rdhhcNRhTcgB+fNwY/BxZMzEmjHD8GhHaLwsHYKRT2lRh7DKuokG41s4JOveQPBlZD1bmfcG4V1YRAvxZungBP8pLtE7olhftBUW00K8IrOvAXymLNsiHvuItsKiWok3s++b4KdWWVbsJ9oKi2slXqFx89rsCfgm8prrK/uKtsIiW4pXpIBPyBfFJ63YX7QVFttyyxLKLLe+OmPtrQUr7lmisfCW4hVVwLfJwForrbVg81whBxRHtOajhKBtl4W1Jpr82FqwQrHKUkzIEcUhPdgiC2O/xCq/aS29fKcXI68fz8ghxTE90XzKVEuIGDtHiLWiOVO0zygOGoFE/JGJadMESLbQ9HKNEKvQnHlP/g44qmfp8AjNXYX8kZFpzcWsOcpcVaiyYaQfNH/Ws1fAYQriqOz7iCrmr4L+EPWFVvs8EuhIkX5FdmVpYAXnKbgzBfQZVXiv2uxklo0CRypTzZR9d0QvlZJEZtlocKq2V2WEJBb5NAXbGpy8SvkwO1kW9AaHq3xIAdv4KAuKK5MREIBa/6aAX5N17GwoGCUoKeDvqCRIwc6MglOCdPdDnF7grGFXREGj3a2M0Frzx4MdUBBpNQvvKOIqVr2oKdgdUWBpO4g4xXpXFPASeAlgdiHLNtmoly7FmvyHxFBEcRbyCDHXeVOoyXUkltIkHAmoCvosaouwz33reBr7X5GqFTOSJI4qrtIktnOTAM/t6/f/9i3DJUmyP79+/QPTTalhHxnmLgAAAABJRU5ErkJggg==" style="width: 32px;"></div><div style="color: #3a3a39;margin-left: 6px;flex-grow:1;">
        ${siteName}<div style="font-size:0.8em;color: #639ee3;">GET — On Shortcuts</div></div><div style="text-align: center;"><a style="text-decoration: none;color: #639ee3;margin-left: 5px;margin-bottom: 4px;display: inline-block;font-size: 0.95em;"
        href="${url}" onclick="localStorage.setItem('_shortcutInstalled','1');document.querySelector(':root').style.transform='';this.parentElement.parentElement.remove();">View</a></div>`

    document.querySelector(":root").style.transform = "translateY(64px)"
    document.querySelector(":root").appendChild(t);
}
